version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: nb
      POSTGRES_PASSWORD: nb
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: todo_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo_db
      SPRING_DATASOURCE_USERNAME: nb
      SPRING_DATASOURCE_PASSWORD: nb
    ports:
      - "8080:8080"
  